import type { ProgressHistory, ProgressRecord } from "@/types/progress";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { readFromStorage, writeToStorage } from "@/lib/storage";

const queueKey = "pending-cloud-sessions-v1";
export function queueProgressForSync(record: ProgressRecord) { const queue = readFromStorage<ProgressRecord[]>(queueKey, []); if (!queue.some((item) => item.sessionId === record.sessionId)) writeToStorage(queueKey, [...queue, record]); }
export function localImportSummary(history: ProgressHistory) { return { sessions: history.sessions.length, questions: history.sessions.reduce((sum, session) => sum + session.questionsAnswered, 0), highestMastery: Math.max(50, ...history.sessions.map((session) => session.masteryAfter)) }; }
/** Idempotent upload uses user_id + stable client_session_id. XP must be awarded by a server-side RPC, never this client helper. */
export async function syncPendingProgress(userId: string) { const client = getSupabaseBrowserClient(); const queue = readFromStorage<ProgressRecord[]>(queueKey, []); if (!client || !navigator.onLine || !queue.length) return { synced: 0, pending: queue.length }; const rows = queue.map((record) => ({ user_id: userId, client_session_id: record.sessionId, session_type: record.sessionType, questions_answered: record.questionsAnswered, correct_answers: record.correctAnswers, accuracy: record.accuracy, mastery_before: record.masteryBefore, mastery_after: record.masteryAfter, mastery_change: record.masteryChange, strongest_skill: record.strongestSkill, weakest_skill: record.weakestSkill, dominant_mistake: record.dominantMistake, highest_difficulty: Math.max(...Object.keys(record.difficultyPerformance).map(Number), 1), session_data: { questionIds: record.questionIds, visualPerformance: record.visualPerformance } })); const { error } = await client.from("progress_sessions").upsert(rows, { onConflict: "user_id,client_session_id", ignoreDuplicates: true }); if (error) return { synced: 0, pending: queue.length, error: error.message }; writeToStorage(queueKey, []); return { synced: rows.length, pending: 0 }; }
