import { estimateMastery, getMistakeCounts, getSkillPerformance } from "@/lib/adaptiveEngine";
import type { AnswerRecord, SATQuestion } from "@/types/question";
import type { MistakeCategory } from "@/types/mistake";
export type MistakeTwinProfile = { dominantMistake: MistakeCategory | "none"; secondaryMistake: MistakeCategory | "none"; strongestSkill: string | null; weakestSkill: string | null; currentMastery: number; confidenceMismatch: string | null; highestStableDifficulty: number; improvementTrend: "improving" | "stable" | "declining"; correctedPatterns: MistakeCategory[]; recommendedSkill: string | null; summary: string };
export type LocalMistakeFeedback = { mistakeType: MistakeCategory; readableMistakeName: string; reasoningSummary: string; whyTheChoiceWasTempting: string; correction: string; hint: string; nextSkill: string; source: "local" };
const summaries: Record<MistakeCategory, string> = { misread_question: "Your Mistake Twin sometimes understands the math but misses an important word or asks for the wrong value.", wrong_operation: "Your Mistake Twin often identifies useful information but combines it using the wrong operation.", wrong_formula: "Your Mistake Twin may recognize the topic but choose a formula that does not match the relationship.", calculation_error: "Your Mistake Twin often understands the setup but loses accuracy during arithmetic or simplification.", solved_wrong_value: "Your Mistake Twin can solve the equation but sometimes stops before answering the exact expression requested.", tempting_distractor: "Your Mistake Twin is drawn to correct intermediate steps rather than the final result.", weak_text_evidence: "Your Mistake Twin can strengthen its evidence checks before choosing a claim.", vocabulary_confusion: "Your Mistake Twin can pause to test a word against its sentence context.", rushed_answer: "Your Mistake Twin becomes stronger when the work is checked before submitting.", visual_misinterpretation: "Your Mistake Twin sometimes misreads a graph, table, scale, label, or diagram before applying the method.", unknown: "Trapwise needs more evidence before identifying a reliable mistake pattern." };
const readable = (value: MistakeCategory) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
export function buildMistakeTwinProfile(records: AnswerRecord[]): MistakeTwinProfile { const counts = Object.entries(getMistakeCounts(records)).sort(([, a], [, b]) => b - a) as [MistakeCategory, number][]; const skills = Object.entries(getSkillPerformance(records)).sort(([, a], [, b]) => (b.correct / b.total) - (a.correct / a.total)); const early = records.slice(0, Math.ceil(records.length / 2)); const late = records.slice(Math.floor(records.length / 2)); const earlyRate = early.filter((item) => item.isCorrect).length / Math.max(early.length, 1); const lateRate = late.filter((item) => item.isCorrect).length / Math.max(late.length, 1); const dominant: MistakeTwinProfile["dominantMistake"] = counts.length ? counts[0][0] : "none"; const confidenceMisses = records.filter((item) => !item.isCorrect && (item.confidence === "certain" || item.confidence === "mostly_sure")); const corrected = records.filter((item) => item.isCorrect).map((item) => item.mistakeCategory).filter((item): item is MistakeCategory => Boolean(item)); return { dominantMistake: dominant, secondaryMistake: counts[1]?.[0] ?? "none", strongestSkill: skills[0]?.[0] ?? null, weakestSkill: skills.at(-1)?.[0] ?? null, currentMastery: estimateMastery(records), confidenceMismatch: confidenceMisses.length ? "Some incorrect answers were submitted with high confidence; pause for a final check." : null, highestStableDifficulty: Math.max(0, ...records.filter((item) => item.isCorrect).map((item) => item.difficultyLevel)), improvementTrend: lateRate > earlyRate + 0.1 ? "improving" : lateRate < earlyRate - 0.1 ? "declining" : "stable", correctedPatterns: [...new Set(corrected)], recommendedSkill: skills.at(-1)?.[0] ?? null, summary: dominant === "none" ? summaries.unknown : summaries[dominant] }; }
export function getLocalMistakeFeedback(question: SATQuestion, selectedChoice: "A" | "B" | "C" | "D"): LocalMistakeFeedback | null { if (selectedChoice === question.correctAnswer) return null; const mistakeType = question.mistakeCategoryByChoice[selectedChoice] ?? "unknown"; return { mistakeType, readableMistakeName: readable(mistakeType), reasoningSummary: `You selected ${selectedChoice}; the verified answer is ${question.correctAnswer}. ${question.explanation}`, whyTheChoiceWasTempting: question.distractorAnalysis[selectedChoice], correction: question.mainTrap, hint: question.fastStrategy, nextSkill: question.primarySkill, source: "local" }; }
