"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ProgressTimeline } from "@/components/ProgressTimeline";
import { getStreak, readProgressHistory } from "@/lib/dailyPractice";
import { readDemoProfile, type DemoProfile } from "@/lib/demoMode";
import type { ProgressHistory } from "@/types/progress";

export default function ProgressPage() {
  const [history, setHistory] = useState<ProgressHistory>({ version: 1, sessions: [] }); const [demo, setDemo] = useState<DemoProfile | null>(null);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { setHistory(readProgressHistory()); setDemo(readDemoProfile()); }); return () => window.cancelAnimationFrame(frame); }, []);
  if (!history.sessions.length) return <main className="mx-auto max-w-3xl px-4 py-10"><p className="text-sm font-semibold uppercase text-emerald-700">Progress dashboard</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Your progress story starts with one practice set.</h1><Link href="/daily" className="mt-6 inline-flex rounded-md bg-emerald-600 px-4 py-2 font-semibold text-white">Start Daily Practice</Link></main>;
  const sessions = history.sessions; const latest = sessions.at(-1)!; const streak = getStreak(history);
  const total = sessions.reduce((sum, item) => sum + item.questionsAnswered, 0); const correct = sessions.reduce((sum, item) => sum + item.correctAnswers, 0); const weeklyChange = sessions.slice(-7).reduce((sum, item) => sum + item.masteryChange, 0);
  const difficulty = sessions.reduce<Record<number, { correct: number; total: number }>>((result, item) => { for (const [level, values] of Object.entries(item.difficultyPerformance)) { const current = result[Number(level)] ?? { correct: 0, total: 0 }; current.correct += values.correct; current.total += values.total; result[Number(level)] = current; } return result; }, {});
  const visual = sessions.reduce((result, item) => { const stats = item.visualPerformance; if (!stats) return result; result.answered += stats.answered; result.correct += stats.correct; result.misreads += stats.visualMisinterpretations; for (const [category, value] of Object.entries(stats.byCategory)) { const current = result.categories[category] ?? { correct: 0, total: 0 }; current.correct += value.correct; current.total += value.total; result.categories[category] = current; } return result; }, { answered: 0, correct: 0, misreads: 0, categories: {} as Record<string, { correct: number; total: number }> });
  return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-sm font-semibold uppercase text-emerald-700">Progress dashboard</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Your learning momentum</h1><p className="mt-3 text-slate-600">Trapwise mastery is an internal learning estimate, not an official SAT score.</p>{demo && <section className="mt-5 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm text-indigo-950"><strong>Fictional demo profile:</strong> {demo.name} · Level {demo.level} · {demo.xp} XP · {demo.streak}-day streak · {demo.achievementKeys.length} achievements</section>}<section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Current mastery" value={String(demo?.mastery ?? latest.masteryAfter)} /><Stat label="Current level" value={`Level ${demo?.level ?? 1}`} /><Stat label="XP" value={String(demo?.xp ?? 0)} /><Stat label="This week" value={`${weeklyChange >= 0 ? "+" : ""}${weeklyChange}`} /><Stat label="Current streak" value={`${demo?.streak ?? streak.active} days`} /><Stat label="Overall accuracy" value={`${Math.round((correct / total) * 100)}%`} /><Stat label="Total questions" value={String(total)} /><Stat label="Mistakes corrected" value={String(sessions.reduce((sum, item) => sum + item.correctedMistakes, 0))} /><Stat label="Strongest skill" value={latest.strongestSkill} /><Stat label="Focus next" value={latest.weakestSkill} /></section><section className="mt-8"><ProgressTimeline sessions={sessions} /></section>{visual.answered > 0 && <section className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-950">Visual reasoning</h2><p className="mt-3 text-sm text-slate-600">{visual.correct}/{visual.answered} correct ({Math.round((visual.correct / visual.answered) * 100)}%)</p><p className="mt-2 text-sm text-slate-600">Visual misinterpretations: {visual.misreads}</p></article><DataBreakdown title="Visual skills" items={Object.entries(visual.categories).map(([category, value]) => [category.replaceAll("_", " "), `${Math.round((value.correct / value.total) * 100)}%`])} /></section>}<section className="mt-8 grid gap-5 lg:grid-cols-2"><DataBreakdown title="Progress by difficulty" items={Object.entries(difficulty).sort(([a], [b]) => Number(a) - Number(b)).map(([level, value]) => [`Level ${level}`, `${Math.round((value.correct / value.total) * 100)}%`])} /><article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-950">Recent practice</h2><div className="mt-4 grid gap-3">{sessions.slice(-7).reverse().map((item) => <div key={item.sessionId} className="rounded-md bg-slate-50 p-3 text-sm"><strong>{item.date}</strong> · {item.accuracy}% · {item.weakestSkill}</div>)}</div></article></section></main>;
}

function Stat({ label, value }: { label: string; value: string }) { return <article className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-bold text-slate-950">{value}</p></article>; }
function DataBreakdown({ title, items }: { title: string; items: [string, string][] }) { return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-slate-950">{title}</h2><ul className="mt-4 grid gap-2">{items.map(([label, value]) => <li key={label} className="flex justify-between rounded-md bg-slate-50 px-3 py-2 text-sm"><span>{label}</span><strong>{value}</strong></li>)}</ul></article>; }
