"use client";
import Link from "next/link";
import { useState } from "react";
import { AuthFormShell } from "@/components/AuthFormShell";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

export default function SignUpPage() {
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(form: HTMLFormElement) { const data = new FormData(form); const displayName = String(data.get("displayName") ?? "").trim(); const email = String(data.get("email") ?? "").trim(); const password = String(data.get("password") ?? ""); const confirmation = String(data.get("confirmation") ?? ""); if (displayName.length < 2 || password.length < 8 || password !== confirmation || !data.get("terms")) { setMessage("Use a display name, an 8-character password, matching passwords, and accept the terms."); return; } const client = getSupabaseBrowserClient(); if (!client) { setMessage("Supabase is not configured yet. Add the values in .env.local."); return; } setLoading(true); const { error } = await client.auth.signUp({ email, password, options: { data: { display_name: displayName }, emailRedirectTo: `${window.location.origin}/login` } }); setLoading(false); setMessage(error ? error.message : "Check your email to verify your account, then sign in."); }
  return <AuthFormShell title="Create your account"><form className="mt-6 grid gap-4" onSubmit={(event) => { event.preventDefault(); void submit(event.currentTarget); }}><label className="grid gap-1 text-sm font-medium">Public display name<input name="displayName" required maxLength={30} className="rounded-md border p-2" /></label><label className="grid gap-1 text-sm font-medium">Email<input name="email" type="email" required autoComplete="email" className="rounded-md border p-2" /></label><label className="grid gap-1 text-sm font-medium">Password<input name="password" type="password" required minLength={8} autoComplete="new-password" className="rounded-md border p-2" /></label><p className="text-xs text-slate-600">Use at least 8 characters. Do not reuse a password from another site.</p><label className="grid gap-1 text-sm font-medium">Confirm password<input name="confirmation" type="password" required autoComplete="new-password" className="rounded-md border p-2" /></label><label className="flex gap-2 text-sm"><input name="terms" type="checkbox" required /> I agree to the Terms and Privacy Notice.</label><button disabled={loading} className="rounded-md bg-emerald-600 px-4 py-2 font-semibold text-white disabled:bg-slate-300">{loading ? "Creating account…" : "Create account"}</button>{message && <p role="status" className="text-sm text-slate-700">{message}</p>}</form><p className="mt-5 text-sm">Already have an account? <Link className="font-semibold text-emerald-700" href="/login">Log in</Link></p></AuthFormShell>;
}
