"use client";
import { useState } from "react";
import { sampleQuestions } from "@/data/sampleQuestions";
import { getLocalMistakeFeedback } from "@/lib/mistakeTwinEngine";
import type { AnswerChoiceId } from "@/types/question";
type Analysis = { source: "ai" | "local"; title: string; whatHappened: string; whyTempting: string; nextStep: string; notice?: string };
type Availability = { aiEnhancedAvailable: boolean; aiUnavailableReason?: string };
function initialAnalysis(questionId: string, selectedChoice: AnswerChoiceId): Analysis { const question = sampleQuestions.find((item) => item.id === questionId); const feedback = question ? getLocalMistakeFeedback(question, selectedChoice) : null; return feedback ? { source: "local", title: "Trapwise Local Analysis", whatHappened: feedback.reasoningSummary, whyTempting: feedback.whyTheChoiceWasTempting, nextStep: feedback.hint, notice: "Verified local question data is the source of truth." } : { source: "local", title: "Trapwise Local Analysis", whatHappened: "Trapwise could not find a verified explanation for this choice.", whyTempting: "No local distractor analysis is available.", nextStep: "Review the verified question explanation.", notice: "Free Tier feedback remains local and verified." }; }
export function MistakeAnalysis({ questionId, selectedChoice }: { questionId: string; selectedChoice: AnswerChoiceId }) { const [analysis, setAnalysis] = useState(() => initialAnalysis(questionId, selectedChoice)); const [loading, setLoading] = useState(false); const [availability, setAvailability] = useState<Availability | null>(null); async function analyzeDeeper() { setLoading(true); try { const response = await fetch("/api/mistake-twin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId, selectedChoice, mode: "ai" }) }); const data = await response.json() as Analysis; if (response.ok) setAnalysis(data); } finally { setLoading(false); } } async function checkAvailability() { const response = await fetch("/api/features"); if (response.ok) setAvailability(await response.json() as Availability); } return <section className="rounded-xl border border-indigo-200 bg-indigo-50 p-5"><p className="text-sm font-semibold uppercase text-indigo-700">Trapwise Local Analysis</p><h2 className="mt-2 text-xl font-bold text-slate-950">Analyze this choice, not just the score.</h2><div className="mt-4 grid gap-3 text-sm text-slate-700"><p><strong>{analysis.title}</strong></p><p>{analysis.whatHappened}</p><p><strong>Why it was tempting:</strong> {analysis.whyTempting}</p><p><strong>Try next:</strong> {analysis.nextStep}</p><p className="text-xs text-slate-600">{analysis.notice}</p><span className="text-xs font-semibold uppercase text-indigo-700">{analysis.source === "ai" ? "AI Enhanced Analysis" : "Verified local feedback"}</span>{analysis.source === "local" && (availability?.aiEnhancedAvailable ? <button type="button" onClick={() => void analyzeDeeper()} disabled={loading} className="w-fit rounded-md border border-indigo-300 px-3 py-2 font-semibold text-indigo-800">{loading ? "Analyzing…" : "Optional AI enhancement: Analyze deeper"}</button> : <button type="button" onClick={() => void checkAvailability()} className="w-fit rounded-md border border-indigo-300 px-3 py-2 font-semibold text-indigo-800">Check optional AI availability</button>)}{availability && !availability.aiEnhancedAvailable && <p className="text-xs text-slate-600">AI Enhanced is optional and currently unavailable ({availability.aiUnavailableReason?.replaceAll("_", " ")}). Free Tier learning remains fully available.</p>}</div></section>; }
