"use client";

import Image from "next/image";
import { useState } from "react";
import type { DiagramVisual, GraphDataVisual, QuestionVisual as QuestionVisualData } from "@/types/visual";

function Diagram({ visual }: { visual: DiagramVisual }) {
  if (visual.diagram === "circle-tangent") return <svg viewBox="0 0 360 180" role="img" aria-label={visual.alt} className="w-full"><circle cx="150" cy="90" r="58" fill="none" stroke="currentColor" strokeWidth="3"/><line x1="208" y1="18" x2="208" y2="162" stroke="currentColor" strokeWidth="3"/><line x1="150" y1="90" x2="208" y2="90" stroke="currentColor" strokeWidth="2"/><text x="132" y="83" fontSize="15">O</text><text x="215" y="83" fontSize="15">T</text><text x="166" y="83" fontSize="14">r</text></svg>;
  if (visual.diagram === "similar-triangles") return <svg viewBox="0 0 360 180" role="img" aria-label={visual.alt} className="w-full"><path d="M35 150 L135 150 L80 35 Z" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M205 150 L325 150 L259 12 Z" fill="none" stroke="currentColor" strokeWidth="3"/><text x="78" y="169" fontSize="14">{visual.labels.smallBase}</text><text x="255" y="169" fontSize="14">{visual.labels.largeBase}</text><text x="83" y="98" fontSize="14">{visual.labels.smallSide}</text><text x="262" y="88" fontSize="14">{visual.labels.largeSide}</text></svg>;
  if (visual.diagram === "floor-plan") return <svg viewBox="0 0 360 180" role="img" aria-label={visual.alt} className="w-full"><rect x="38" y="32" width="260" height="116" fill="none" stroke="currentColor" strokeWidth="4"/><line x1="145" y1="32" x2="145" y2="148" stroke="currentColor" strokeWidth="3"/><line x1="145" y1="88" x2="298" y2="88" stroke="currentColor" strokeWidth="3"/><text x="65" y="91" fontSize="16">Studio</text><text x="181" y="67" fontSize="16">Lab</text><text x="178" y="122" fontSize="16">Hall</text><text x="109" y="23" fontSize="14">{visual.labels.width}</text><text x="305" y="95" fontSize="14">{visual.labels.height}</text></svg>;
  return <svg viewBox="0 0 360 180" role="img" aria-label={visual.alt} className="w-full"><rect x="55" y="55" width="85" height="55" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M140 82 H235 M235 82 l-12 -9 M235 82 l-12 9" stroke="currentColor" strokeWidth="3" fill="none"/><rect x="240" y="55" width="65" height="55" fill="none" stroke="currentColor" strokeWidth="3"/><text x="67" y="86" fontSize="13">Control</text><text x="248" y="86" fontSize="13">Test</text><text x="152" y="48" fontSize="13">{visual.labels.variable}</text></svg>;
}

function Graph({ visual }: { visual: GraphDataVisual }) {
  const width = 440; const height = 255; const pad = 38;
  const x = (value: number) => pad + ((value - visual.xDomain[0]) / (visual.xDomain[1] - visual.xDomain[0])) * (width - pad * 2);
  const y = (value: number) => height - pad - ((value - visual.yDomain[0]) / (visual.yDomain[1] - visual.yDomain[0])) * (height - pad * 2);
  return <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={visual.alt} className="w-full"><line x1={pad} x2={width - pad} y1={height - pad} y2={height - pad} stroke="currentColor"/><line x1={pad} x2={pad} y1={pad} y2={height - pad} stroke="currentColor"/>{visual.series.map((series, index) => series.style === "bar" ? <g key={series.id}>{series.points.map((point) => <g key={`${point.x}-${point.y}`}><rect x={x(point.x) - 13} y={y(point.y)} width="26" height={y(0) - y(point.y)} fill={index ? "#f59e0b" : "#059669"}/>{point.label && <text x={x(point.x)} y={height - pad + 16} textAnchor="middle" fontSize="11">{point.label}</text>}</g>)}</g> : <g key={series.id}>{series.style === "line" || series.style === "parabola" ? <polyline points={series.points.map((point) => `${x(point.x)},${y(point.y)}`).join(" ")} fill="none" stroke={index ? "#f59e0b" : "#059669"} strokeWidth="3"/> : null}{series.points.map((point) => <circle key={`${point.x}-${point.y}`} cx={x(point.x)} cy={y(point.y)} r="4" fill={index ? "#f59e0b" : "#059669"}/>)}</g>)}<text x={width / 2} y={height - 7} textAnchor="middle" fontSize="12">{visual.xLabel}</text><text x="13" y={height / 2} textAnchor="middle" fontSize="12" transform={`rotate(-90 13 ${height / 2})`}>{visual.yLabel}</text></svg>;
}

export function QuestionVisual({ visual }: { visual: QuestionVisualData }) {
  const [failed, setFailed] = useState(false);
  return <figure className="mt-5 overflow-hidden rounded-xl border border-slate-200 bg-slate-50 p-4 text-slate-800"><div className="min-h-32">{visual.kind === "table" && <table className="w-full border-collapse text-left text-sm"><thead><tr>{visual.columns.map((column) => <th key={column} className="border-b border-slate-300 p-2 font-semibold">{column}</th>)}</tr></thead><tbody>{visual.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex} className="border-b border-slate-200 p-2">{cell}</td>)}</tr>)}</tbody></table>}{visual.kind === "graph-data" && <Graph visual={visual} />}{visual.kind === "diagram" && <Diagram visual={visual} />}{visual.kind === "svg" && <div role="img" aria-label={visual.alt} className="flex min-h-32 items-center justify-center rounded-lg border border-dashed border-slate-300 p-4 text-center text-sm">{visual.safeDescription}</div>}{visual.kind === "image" && (failed ? <button type="button" onClick={() => setFailed(false)} className="min-h-32 w-full rounded-lg border border-dashed border-slate-300 p-4 text-sm">The image is unavailable. Retry loading the visual.</button> : <div className="relative"><Image src={visual.src} alt={visual.alt} width={visual.width} height={visual.height} onError={() => setFailed(true)} className="h-auto w-full rounded-lg"/>{visual.overlays?.map((overlay) => <span key={overlay.id} className="absolute rounded bg-slate-950/80 px-1.5 py-0.5 text-xs text-white" style={{ left: `${overlay.xPercent}%`, top: `${overlay.yPercent}%` }} aria-label={overlay.description}>{overlay.label}</span>)}</div>)}</div><figcaption className="mt-3 text-sm leading-6 text-slate-600">{visual.caption}</figcaption></figure>;
}
