-- Run in the Supabase SQL editor. All learner data is protected by RLS.
create extension if not exists citext;
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 30),
  username citext unique check (username ~ '^[a-zA-Z0-9_]{3,20}$'), avatar_key text default 'owl', bio text default '',
  is_profile_public boolean not null default false, show_on_leaderboards boolean not null default false,
  current_level integer not null default 1, total_xp integer not null default 0 check (total_xp >= 0), current_mastery integer not null default 50 check (current_mastery between 0 and 100), current_streak integer not null default 0, longest_streak integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.progress_sessions (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, client_session_id text not null, session_type text not null check (session_type in ('diagnostic','daily','follow-up','trap-forge','challenge')), completed_at timestamptz not null default now(), questions_answered integer not null check (questions_answered >= 0), correct_answers integer not null check (correct_answers between 0 and questions_answered), accuracy integer not null check (accuracy between 0 and 100), mastery_before integer not null check (mastery_before between 0 and 100), mastery_after integer not null check (mastery_after between 0 and 100), mastery_change integer not null, strongest_skill text, weakest_skill text, dominant_mistake text, highest_difficulty integer check (highest_difficulty between 1 and 5), xp_earned integer not null default 0 check (xp_earned >= 0), session_data jsonb not null default '{}'::jsonb, unique(user_id, client_session_id)
);
create table if not exists public.skill_progress (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, skill_key text not null, questions_answered integer not null default 0, correct_answers integer not null default 0, accuracy integer not null default 0, mastery integer not null default 0, highest_difficulty integer not null default 1, last_practiced_at timestamptz, unique(user_id, skill_key));
create table if not exists public.mistake_patterns (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, mistake_category text not null, occurrence_count integer not null default 0, corrected_count integer not null default 0, recognition_progress integer not null default 0, last_detected_at timestamptz, unique(user_id, mistake_category));
create table if not exists public.achievements (id uuid primary key default gen_random_uuid(), key text unique not null, name text not null, description text not null, icon_key text not null, category text not null, xp_reward integer not null default 0, requirement_type text not null, requirement_value integer not null, is_hidden boolean not null default false);
create table if not exists public.user_achievements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, achievement_id uuid not null references public.achievements(id), unlocked_at timestamptz, progress integer not null default 0, is_new boolean not null default true, unique(user_id, achievement_id));
create table if not exists public.daily_activity (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, activity_date date not null, completed_daily boolean not null default false, questions_answered integer not null default 0, xp_earned integer not null default 0, mastery_change integer not null default 0, unique(user_id, activity_date));
create table if not exists public.leaderboard_groups (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null check(char_length(name) between 2 and 40), join_code text unique not null, is_private boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.leaderboard_group_members (group_id uuid references public.leaderboard_groups(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, joined_at timestamptz not null default now(), primary key(group_id,user_id));
alter table public.profiles enable row level security; alter table public.progress_sessions enable row level security; alter table public.skill_progress enable row level security; alter table public.mistake_patterns enable row level security; alter table public.user_achievements enable row level security; alter table public.daily_activity enable row level security; alter table public.leaderboard_groups enable row level security; alter table public.leaderboard_group_members enable row level security; alter table public.achievements enable row level security;
create policy "profiles own" on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());
create policy "sessions own" on public.progress_sessions for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "skills own" on public.skill_progress for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "mistakes own" on public.mistake_patterns for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "user achievements own" on public.user_achievements for select using (user_id = auth.uid());
create policy "activity own" on public.daily_activity for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "achievement definitions readable" on public.achievements for select using (true);
create policy "groups owner manages" on public.leaderboard_groups for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "members see own memberships" on public.leaderboard_group_members for select using (user_id = auth.uid());
-- Public leaderboard clients should query a SECURITY DEFINER view/RPC that returns only opted-in display_name, avatar_key, level, rank, and verified score. Never expose email, raw user_id, sessions, or Mistake Twin details.
